### ISSUE TITLE
MicroService - CDN

### ISSUE THREAD

**Issue by marconneves** [B4-Org/.github#9]
Aqui temos o planejamento do nosso novo micro serviço de CDN, a idéia é usara partir de agora os real links dos storage do google, e não uma mascara interna.

- [x] B4-Org/B4_Api_CDN#1
- [x] B4-Org/B4_Api_CDN#2
- [ ] B4-Org/B4_Api_CDN#3

Atualização de versões antigas:
- [ ] B4-Org/.github#10
- [ ] B4-Org/.github#11
- [ ] B4-Org/.github#12
- [ ] B4-Org/.github#13

**Comment by marconneves** [comment]
Fiz uma POC para testar a criação de uma URL assinada.
https://github.com/B4-Org/POC_Study/pull/1/files

**Comment by themarkwill** [comment]
- [ ] CDN - Criar estrutura do repositório
- [ ] CDN - Upload de arquivo para storage público
- [ ] CDN - Upload de arquivo para storage privado
- [ ] CDN - Gerar url temporaria de arquivo privado
